config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }

  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords"
  }

  namespace :admins do
    resources :ingredients, only: [:new, :create, :index, :destroy]
    #   get 'ingredients/new'
    #   get 'ingredients/create'
    #   get 'ingredients/index'
    resources :users, only: [:index, :show, :edit, :update]
    #   get 'users/index'
    #   get 'users/show'
    #   get 'users/edit'
    #   patch 'users/update'
    resources :genres, only: [:index, :create, :edit, :update, :new]
    # get 'genres/index'
    # post 'genres/create'
    # get 'genres/edit'
    # patch 'genres/update'
    resources :recipes
    # get 'recipes/index'
    # get 'recipes/new'
    # post 'recipes/create'
    # patch 'recipes/update'
    # get 'recipes/show'
    # get 'recipes/edit'
    # resources :homes, only: [:top]
    get "homes/top"


  end

  namespace :users do
    post 'recipes/:id/favorites', to: 'favorites#create', as: :favorites
    delete 'recipes/:id/favorites', to: 'favorites#destroy', as: :destroy_favorites
    resources :users, only: [:show, :edit, :update, :create]
    resources :calorie_dentakus, only: [:index, :destroy]
    # get 'calorie_dentakus/show'
    resources :sessions, only: [:new, :create, :destroy]
    # get 'sessions/new'
    # post 'sessions/create'
    # delete 'sessions/destroy'
    resources :homes, only: [] do
      collection do
        get :top
        get :about
      end
    end
    # get 'homes/top'
    # get 'homes/about'
    resources :mymemos_ingredients, only: [:destroy]
    resources :ingredients, only: [:index]
    resources :mymemos, only: [:show, :destroy, :create]
    resources :recipes, only: [:create, :new, :index, :show, :destroy] do
      collection do
        get :search
      end
    end
    post 'recipes/:id/post_comments', to: 'post_comments#create', as: :post_comments
    delete 'recipes/:id/post_comments/:post_comments_id', to: 'post_comments#destroy', as: :destroy_post_comments
  end
  post "/users/recipes/new", to: "users/recipes#new"
  root to: "users/homes#top"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  self.inheritance_column = "not_sti"
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :mymemos_ingredients, dependent: :destroy
  paginates_per 8
  belongs_to :recipe, optional: true
  has_one_attached :image

  attribute :amount, :integer

  def total(amount)
    calorie * amount
  end
end

app/models/mymemo.rb
class Mymemo < ApplicationRecord
  belongs_to :user
  has_many :mymemos_ingredients, dependent: :destroy
  has_many :ingredients, through: :mymemos_ingredients

  def total_calorie
    mymemos_ingredients.sum do |mymemos_ingredient|
      mymemos_ingredient.ingredient.total(mymemos_ingredient.amount)
    end
  end
end

app/models/mymemos_ingredient.rb
class MymemosIngredient < ApplicationRecord
  belongs_to :mymemo
  belongs_to :ingredient

  def total_calorie
    ingredient.calorie * amount
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  paginates_per 8
  has_one_attached :image
  belongs_to :admin, optional: true
  belongs_to :user, optional: true
  belongs_to :genre
  has_many :ingredients
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.search_by(search_term)
    if search_term.present?
      where("LOWER(recipe_name) LIKE :search_term",
      search_term: "%#{search_term.downcase}%")
    else
      Recipe.all
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :mymemos
  has_many :mymemos_ingredients, through: :mymemos
  belongs_to :admin, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/admins/genres_controller.rb
# frozen_string_literal: true

class Admins::GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def new
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to new_admins_genre_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to new_admins_genre_path
  end

  def category1
  end

  def category2
  end

  def category3
  end

  def category4
  end

  private
    def genre_params
      params.require(:genre).permit(:genre_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController <
  ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :birthday])
    end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/users/my_memo_helper.rb
module Users::MyMemoHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/genres/edit.html.erb
<section class="hero is-small">

  <div class="hero-body">
    <p class="title has-text-centered has-text-link">
      ジャンル編集
    </p>
  </div>

<%= form_with model: @genre, url: edit_admins_genre_path, method: :get do |f| %>

  <div class="field is-horizontal is-centered">
  <div class="column columns is-centered mb-2 ml-6">

  <div class="field-label">
    <label class="label has-text-info">ジャンル名 </label>

  </div>
  <div class="field-body">
    <div class="field is-narrow">
      <div class="control">
        <%= f.text_field :genre_name %>
      </div>
    </div>
  </div>

  <div class="field-body">
    <div class="field is-narrow">
    <div class="control">
        <%= f.submit '変更を保存', class: "button is-success" %>
    </div>
  </div>
  </div>

  </div>
  </div>

 <% end %>

</section>

app/views/admins/genres/new.html.erb
<section class="hero is-small">

  <div class="hero-body">
    <p class="title has-text-centered has-text-link">
      ジャンル一覧・作成
    </p>
  </div>

<%= form_with model: @genre, url: admins_genres_path, method: :post do |f| %>

  <div class="field is-horizontal is-centered">
  <div class="column columns is-centered mb-2 ml-6">

  <div class="field-label">
    <label class="label has-text-info">ジャンル名 </label>

  </div>
  <div class="field-body">
    <div class="field is-narrow">
      <div class="control">
        <%= f.text_field :genre_name %>
      </div>
    </div>
  </div>

  <div class="field-body">
    <div class="field is-narrow">
    <div class="control">
        <%= f.submit '新規登録', class: "button is-success" %>
    </div>
  </div>
  </div>

  </div>
  </div>

 <% end %>
<div class="column is-half is-offset-one-quarter">
<table class="table table is-bordered">
     <thead class="has-background-primary-light">
      <tr>
      <th>ジャンル</th>
      <th></th>
      </tr>
      </thead>

      <tfoot>
      <% @genres.each do |genre| %>
      <tr>
      <th>
        <%# byebug %>
        <%= genre.genre_name %>
      </th>
      <th><%= link_to "編集", edit_admins_recipe_path(genre.id), class:"button has-text-warning-light has-background-info-dark"%></th>
      </tr>
      <% end %>
      </tfoot>
  </table>
</div>

</section>

app/views/admins/genres/update.html.erb
<h1>Admins::Genres#update</h1>
<p>Find me in app/views/admins/genres/update.html.erb</p>