config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }

  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords"
  }

  namespace :admins do
    resources :ingredients, only: [:new, :create, :index, :destroy]
    #   get 'ingredients/new'
    #   get 'ingredients/create'
    #   get 'ingredients/index'
    resources :users, only: [:index, :show, :edit, :update]
    #   get 'users/index'
    #   get 'users/show'
    #   get 'users/edit'
    #   patch 'users/update'
    resources :genres, only: [:index, :create, :edit, :update, :new]
    # get 'genres/index'
    # post 'genres/create'
    # get 'genres/edit'
    # patch 'genres/update'
    resources :recipes
    # get 'recipes/index'
    # get 'recipes/new'
    # post 'recipes/create'
    # patch 'recipes/update'
    # get 'recipes/show'
    # get 'recipes/edit'
    # resources :homes, only: [:top]
    get "homes/top"


  end

  namespace :users do
    post 'recipes/:id/favorites', to: 'favorites#create', as: :favorites
    delete 'recipes/:id/favorites', to: 'favorites#destroy', as: :destroy_favorites
    resources :users, only: [:show, :edit, :update, :create]
    resources :calorie_dentakus, only: [:index, :destroy]
    # get 'calorie_dentakus/show'
    resources :sessions, only: [:new, :create, :destroy]
    # get 'sessions/new'
    # post 'sessions/create'
    # delete 'sessions/destroy'
    resources :homes, only: [] do
      collection do
        get :top
        get :about
      end
    end
    # get 'homes/top'
    # get 'homes/about'
    resources :mymemos_ingredients, only: [:destroy]
    resources :ingredients, only: [:index]
    resources :mymemos, only: [:show, :destroy, :create]
    resources :recipes, only: [:create, :new, :index, :show, :destroy] do
      collection do
        get :search
      end
    end
    post 'recipes/:id/post_comments', to: 'post_comments#create', as: :post_comments
    delete 'recipes/:id/post_comments/:post_comments_id', to: 'post_comments#destroy', as: :destroy_post_comments
  end
  post "/users/recipes/new", to: "users/recipes#new"
  root to: "users/homes#top"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  self.inheritance_column = "not_sti"
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :mymemos_ingredients, dependent: :destroy
  paginates_per 8
  belongs_to :recipe, optional: true
  has_one_attached :image

  attribute :amount, :integer

  def total(amount)
    calorie * amount
  end
end

app/models/mymemo.rb
class Mymemo < ApplicationRecord
  belongs_to :user
  has_many :mymemos_ingredients, dependent: :destroy
  has_many :ingredients, through: :mymemos_ingredients

  def total_calorie
    mymemos_ingredients.sum do |mymemos_ingredient|
      mymemos_ingredient.ingredient.total(mymemos_ingredient.amount)
    end
  end
end

app/models/mymemos_ingredient.rb
class MymemosIngredient < ApplicationRecord
  belongs_to :mymemo
  belongs_to :ingredient

  def total_calorie
    ingredient.calorie * amount
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  paginates_per 8
  has_one_attached :image
  belongs_to :admin, optional: true
  belongs_to :user, optional: true
  belongs_to :genre
  has_many :ingredients
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.search_by(search_term)
    if search_term.present?
      where("LOWER(recipe_name) LIKE :search_term",
      search_term: "%#{search_term.downcase}%")
    else
      Recipe.all
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :mymemos
  has_many :mymemos_ingredients, through: :mymemos
  belongs_to :admin, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/admins/ingredients_controller.rb
# frozen_string_literal: true

class Admins::IngredientsController < ApplicationController
  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save!
      redirect_to admins_ingredients_path
    else
      render :new
    end
  end

  def index
    @ingredients = Ingredient.page(params[:page]).per(8)
  end

  def destroy
    ingredient = Ingredient.find_by_id(params[:id])
    ingredient.destroy
    redirect_to admins_ingredients_path, notice: "材料を削除しました。"
  end

  private
    def ingredient_params
      params.require(:ingredient).permit(:ingredient_name, :image, :calorie)
    end
end

app/controllers/application_controller.rb
class ApplicationController <
  ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :birthday])
    end
end

app/controllers/users/ingredients_controller.rb
class Users::IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.page(params[:page]).per(8)

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/ingredients_helper.rb
module Admins::IngredientsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/ingredients/index.html.erb
<div class="box">
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

        <div class="container">
          <h1 class="title has-text-centered has-text-link">材料一覧</h1>
        </div></br>

          <div clas="m-4"><%= link_to "材料 作成" , new_admins_ingredient_path, class:"button has-background-success-light" %></div></br></br>

           <table class="table table is-bordered">
             <thead class="has-background-primary-light">
                <tr>
                  <th>材料画像</th>
                  <th>材料名</th>
                  <th>カロリー数</th>
                  <th></th>
                </tr>
              </thead>

              <tfoot>
                <% @ingredients.each do |ingredient| %>
                <tr>
                  <th><%= image_tag ingredient.image, size: "30x30" %></th>
                  <th class="p-4"><%= ingredient.ingredient_name %></th>
                  <th class="p-4"><%= ingredient.calorie %></th>
                  <th><%= link_to "削除", admins_ingredient_path(ingredient.id), method: :delete,class:"button is-danger","data-confirm"=>"本当に削除しますか？" %></th>
                </tr>
                <% end %>
              </tfoot>
            </table>

        </div>
        <div class="row">
          <div style="position:relative; width:33.3333%; padding-right: 15px; padding-left:15px; margin-left: 33.3333%;">
          <!--div class="col-3 offset-3"-->
           <%= paginate @ingredients %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/ingredients/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">

        <div class="container">
          <h1 class="title has-text-centered has-text-link">材料作成</h1>
        </div></br>

<%= form_with model: @ingredient, url: admins_ingredients_path, method: :post do |f| %>

<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label has-text-info">材料画像</label>
  </div>
  <div class="field-body">
    <div class="field is-narrow">
      <div class="control">
          <div class="control">
            <%= f.file_field :image, accept: "image/*" %>
          </div>
        </div>
    </div>
  </div>
</div>

<div class="field is-horizontal">
  <div class="field-label">
    <label class="label has-text-info">材料名</label>
  </div>
  <div class="field-body">
    <div class="field is-narrow">
      <div class="control">
        <%= f.text_field :ingredient_name %>
      </div>
    </div>
  </div>
</div>

<div class="field is-horizontal">
  <div class="field-label">
    <label class="label has-text-info">カロリー数</label>
  </div>
  <div class="field-body">
    <div class="field is-narrow">
      <div class="control">
        <%= f.number_field :calorie %>
      </div>
    </div>
  </div>
</div>

<div class="field is-horizontal">
  <div class="field-label">
    <!-- Left empty for spacing -->
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <div class="action">
          <%= f.submit '投稿', class: "button is-success" %>
        </div>
      </div>
    </div>
  </div>
</div>
 <% end %>
    </div>
    </div>
  </div>
</section>