config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }

  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords"
  }

  namespace :admins do
    resources :ingredients, only: [:new, :create, :index, :destroy]
    #   get 'ingredients/new'
    #   get 'ingredients/create'
    #   get 'ingredients/index'
    resources :users, only: [:index, :show, :edit, :update]
    #   get 'users/index'
    #   get 'users/show'
    #   get 'users/edit'
    #   patch 'users/update'
    resources :genres, only: [:index, :create, :edit, :update, :new]
    # get 'genres/index'
    # post 'genres/create'
    # get 'genres/edit'
    # patch 'genres/update'
    resources :recipes
    # get 'recipes/index'
    # get 'recipes/new'
    # post 'recipes/create'
    # patch 'recipes/update'
    # get 'recipes/show'
    # get 'recipes/edit'
    # resources :homes, only: [:top]
    get "homes/top"


  end

  namespace :users do
    post 'recipes/:id/favorites', to: 'favorites#create', as: :favorites
    delete 'recipes/:id/favorites', to: 'favorites#destroy', as: :destroy_favorites
    resources :users, only: [:show, :edit, :update, :create]
    resources :calorie_dentakus, only: [:index, :destroy]
    # get 'calorie_dentakus/show'
    resources :sessions, only: [:new, :create, :destroy]
    # get 'sessions/new'
    # post 'sessions/create'
    # delete 'sessions/destroy'
    resources :homes, only: [] do
      collection do
        get :top
        get :about
      end
    end
    # get 'homes/top'
    # get 'homes/about'
    resources :mymemos_ingredients, only: [:destroy]
    resources :ingredients, only: [:index]
    resources :mymemos, only: [:show, :destroy, :create]
    resources :recipes, only: [:create, :new, :index, :show, :destroy] do
      collection do
        get :search
      end
    end
    post 'recipes/:id/post_comments', to: 'post_comments#create', as: :post_comments
    delete 'recipes/:id/post_comments/:post_comments_id', to: 'post_comments#destroy', as: :destroy_post_comments
  end
  post "/users/recipes/new", to: "users/recipes#new"
  root to: "users/homes#top"

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  paginates_per 8
  has_one_attached :image
  belongs_to :admin, optional: true
  belongs_to :user, optional: true
  belongs_to :genre
  has_many :ingredients
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.search_by(search_term)
    if search_term.present?
      where("LOWER(recipe_name) LIKE :search_term",
      search_term: "%#{search_term.downcase}%")
    else
      Recipe.all
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :mymemos
  has_many :mymemos_ingredients, through: :mymemos
  belongs_to :admin, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/admins/recipes_controller.rb
# frozen_string_literal: true

class Admins::RecipesController < ApplicationController
  def index
    @recipes = Recipe.page(params[:page]).per(6)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_admin.recipes.new(recipe_params)
    if @recipe.save
      redirect_to admins_homes_top_path
    else
      render :new
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      flash[:notice] = "You have updated recipe successfully."
      redirect_to admins_recipe_path(@recipe.id)
    else
      render :edit
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def destroy
    recipe = Recipe.find_by_id(params[:id])
    recipe.destroy
    redirect_to admins_recipes_path, notice: "レシピを削除しました。"
  end

  private
    def recipe_params
      params.require(:recipe).permit(:recipe_name, :image, :body, :nutrition, :genre_id, :composition)
    end
end

app/controllers/admins/users_controller.rb
# frozen_string_literal: true

class Admins::UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users/calorie_dentakus_controller.rb
class Users::CalorieDentakusController < ApplicationController
  def index
    items = JSON.parse(params[:ingredients]) # it`s javasript code for object method
    @ingredients = items.each.map do |k, v| # for bringing key and value from item to delete directly
      # binding.pry
      if v != 0 || params[:delete_ingredient] != k # when it`s not zero or sending the params
        ingredient = Ingredient.find(k)
        ingredient.amount = v
        ingredient
      end
    end.compact

    @total = @ingredients.map { |o| o.calorie * o.amount }.sum
    @resources = @ingredients.map { |o| { id: o.id, amount: o.amount } }
    params[:ingredients] = Hash[*@ingredients.map { |o| [o.id, o.amount] }.flatten].to_json
  end

  def create
    # 「メモをしましょう」ボタンをおしたとき

    # @ingredient.update(amount: ingredient[:amount].to_i)
    # mymemo.mymemos_ingredients.new(ingredient_id: @ingredient.id).save
  end

  def destroy
    ingredient = Ingredient.find_by_id(params[:id])
    ingredient.destroy
    redirect_to users_calorie_dentakus_path, notice: "レシピを削除しました。"
  end

  private

    def calorie_dentaku_params
      params.require(:calorie_dentaku).permit(:calorie, :amount, :ingredient_name)
    end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController
before_action :authenticate_user!
  def create
    recipe = Recipe.find(params[:id])
    favorite = current_user.favorites.new(recipe_id: recipe.id)
    favorite.save!
    redirect_to users_recipe_path(recipe.id)
  end

  def destroy
    recipe = Recipe.find(params[:id])
    favorite = current_user.favorites.find_by(recipe_id: recipe.id)
    favorite.destroy
    redirect_to users_recipe_path(recipe)
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/ingredients_controller.rb
class Users::IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.page(params[:page]).per(8)

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/users/mymemos_controller.rb
class Users::MymemosController < ApplicationController
  def show
    @mymemo = current_user.mymemos.find_by_id(params[:id])
    @mymemo.ingredients.each do |item|
      # binding.pry
      @mymemo.mymemos_ingredients.each do |m|
        if item[:ingredient_id] == m[:ingredient_id]
          item["amount"] = m.amount
        end
      end
    end
  end

  def create
    # param(String) to @resouces(Hash)
    mymemo = current_user.mymemos.new
    params[:ingredient].each do |ingredient|
      id, amount = ingredient.split(" ")
      mymemo.mymemos_ingredients.new(ingredient_id: id, amount:)
    end
    # User.new(name: "aa").save
    # User.create(name: "aa")
    mymemo.save!
    redirect_to users_mymemo_path(mymemo.id)
  end

  def destroy
    # binding.pry
    ingredient = Ingredient.find(params[:id])
    # ingredient.destroy
    ingredient.update(amount: 0)
    redirect_to users_mymemo_path, notice: "メモを削除しました。"
  end

  def ingredient_params
    params.require(:ingredient).permit(:ingredient_name, :calorie, :amount, :user_id)
  end
end

app/controllers/users/mymemos_ingredients_controller.rb
class Users::MymemosIngredientsController < ApplicationController
  def destroy
    mymemos_ingredient = current_user.mymemos_ingredients.find(params[:id])
    mymemos_ingredient.destroy!
    redirect_to users_mymemo_path(mymemos_ingredient.mymemo)
  end
end

app/controllers/users/post_comments_controller.rb
class  Users::PostCommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    recipe = Recipe.find(params[:id])
    comment = current_user.post_comments.new(post_comment_params)
    # 以下のように記述したものと変わりません。
    # comment = PostComment.new(post_comment_params)
    # comment.user_id = current_user.id
    comment.recipe_id = recipe.id
    comment.save!
    redirect_to users_recipe_path(comment.recipe_id)
  end

  def destroy
    recipe = Recipe.find(params[:id])
    PostComment.find(params[:post_comments_id]).destroy
    redirect_to users_recipe_path(recipe.id)
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/users/recipes_controller.rb
class Users::RecipesController < ApplicationController
  def index
    if params[:genre_id].present?
      genre = Genre.find(params[:genre_id])
      @recipes = genre.recipes.page(params[:page]).per(6)
    else
      @recipes = Recipe.where.not(admin_id: nil)
      @recipes = @recipes.page(params[:page]).per(6)
    end
    if params[:search].present?
      @recipes = Recipe.search_by(params[:search])
      @recipes = @recipes.page(params[:page]).per(6)
    end
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to users_recipe_path(@recipe.id)
    else
      render :new
    end
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @post_comment = PostComment.new
  end

  def search
    @recipes = Recipe.search(params[:search])
  end

  def destroy
    recipe = Recipe.find_by_id(params[:id])
    user = recipe.user
    recipe.destroy
    redirect_to users_user_path(user.id), notice: "レシピを削除しました。"
  end

  def recipe_params
    params.require(:recipe).permit(:recipe_name, :image, :body, :nutrition, :genre_id, :composition)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  protected

    def after_sign_in_path_for(user)
      about_users_homes_path
    end

    def after_sign_out_path_for(user)
      root_path
    end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  def show
    if params[:id].to_i == current_user.id
      @user = User.find(params[:id])
      @recipe = @user.recipes.last
    else
      redirect_to root_path
    end
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to users_user_path
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :birthday, :email)
    end
end

app/helpers/admins/recipes_helper.rb
module Admins::RecipesHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/calorie_dentaku_helper.rb
module Users::CalorieDentakuHelper
end

app/helpers/users/my_memo_helper.rb
module Users::MyMemoHelper
end

app/helpers/users/mymemos_ingredients_helper.rb
module Users::MymemosIngredientsHelper
end

app/views/users/recipes/index.html.erb
<section class="section has-background-warning-dark">
    <div class="columns is-multiline">
      <% @recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to admins_recipes_path(recipe) do %>
                  <%# unless recipe.image.nill? %>
                    <%= image_tag recipe.image %>
                  <%# end %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <h2><%= recipe.recipe_name %></h2>
                </div>
                <div class="media-content">
                  <div class="titzale"><%#=link_to recipe.user.name, users_user_path(recipe.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %></time>
                <%= link_to "もっと見る", users_recipe_path(recipe.id), class:"button is-link" %>
                <p><%= link_to "#{recipe.post_comments.count} コメント", users_recipe_path(recipe.id) %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <div style="position:relative; width:33.3333%; padding-right: 15px; padding-left:15px; margin-left: 33.3333%;">
          <!--div class="col-3 offset-3"-->
          <%= paginate @recipes %>
  </div>
</section>

app/views/users/recipes/new.html.erb
<section class="section">
  <div class="container has-background-success-light">
    <div class="columns is-centered">
      <div class="column is-7">

        <div class="container">
          <h1 class="title has-text-centered has-text-link">レシピ新規登録</h1>
        </div></br>

          <%= form_with model: @recipe, url: users_recipes_path, method: :post do |f| %>
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label has-text-info">レシピ画像</label>
              </div>
                <div class="field-body">
                  <div class="field is-narrow">
                    <div class="control">
                      <div class="control">
                        <%= f.file_field :image, accept: "image/*" %>
                      </div>
                    </div>
                </div>
                </div>
            </div>
            
            <div class="field is-horizontal">
              <div class="field-label">
                <label class="label has-text-info">レシピ名</label>
              </div>
              <div class="field-body">
                <div class="field is-narrow">
                  <div class="control">
                    <%= f.text_field :recipe_name %>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label has-text-info">作り方</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                     <%= f.text_area :body %>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label has-text-info">ジャンル</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                    <%= f.collection_select :genre_id, Genre.all, :id, :genre_name %></div>
                </div>
              </div>
            </div>
            
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label has-text-info">材料</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                     <%= f.text_area :composition %>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label has-text-info">情報 栄養</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                     <%= f.text_area :nutrition %>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="field is-horizontal">
              <div class="field-label">
                <!-- Left empty for spacing -->
              </div>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                    <div class="action">
                      <%= f.submit '投稿', class: "button is-success" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
             <% end %>
                </div>
                </div>
  </div>
</section>

app/views/users/recipes/show.html.erb
<div class="box">


    <div class="tile is-ancestor">
      <div class="tile is-vertical is-12">
        <div class="tile">
          <div class="tile is-parent">
            <article class="tile is-child notification is-info">
              <p class="title has-text-centered"><%= @recipe.recipe_name %></p>
              <figure class="image is-3by4">
                <%= image_tag @recipe.image %>
              </figure>
            </article>
          </div>

          <div class="tile is-8 is-vertical">
            <div class="tile">

              <div class="tile is-parent has-background-warning-light">
                <article class="tile is-child box">
                  <p class="title">材料</p>
                  <h4><%= @recipe.composition %></h4>
                </article>
              </div>

              <div class="tile is-parent has-background-warning-light">
                <article class="tile is-child box">
                  <p class="title">情報 栄養</p>
                  <p class="subtitle"><%= @recipe.nutrition %></p>
                </article>
              </div>
            </div>

            <div class="tile is-parent has-background-warning-light">
              <article class="tile is-child box">
                <p class="title">作り方</p>
                <p class="subtitle"><%= @recipe.body %></p>
              </article>
            </div>

            <div class="tile is-parent has-background-danger-light">
              <article class="media">
                <div class="media-left">
                  <div>
                    <%= form_with model: [@recipe, @post_comment], url: users_post_comments_path do |f| %>
                      <%#= f.hidden_field :recipe_id, value: @recipe.id %>
                      <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %></br>
                      <%= f.submit "送信する", class:"button is-primary" %>
                    <% end %>
                  </div>
                </div>
                <div class="media-content">
                  <div class="content">
                    <div>
                      <strong class="">コメント件数：</strong> <small><%= @recipe.post_comments.count %></small>
                      <br>
                       <div>
                           <% @recipe.post_comments.each do |post_comment| %>
                             <div><%= post_comment.user.name %>
                             <%= post_comment.created_at.strftime('%Y/%m/%d') %>
                             <%= post_comment.comment %>
                             <% if post_comment.user == current_user %>
                              <%= link_to "削除", users_destroy_post_comments_path(id: post_comment.recipe, post_comments_id: post_comment), method: :delete %>
                             <% end %>
                             </div>
                           <% end %>
                       </div>
                    </div>
                  </div>
                  <nav class="level is-mobile">
                            <!--「いいね機能」-->
                    <% if user_signed_in? && @recipe.favorited_by?(current_user) %>
                      <p>
                        <%= link_to users_destroy_favorites_path(@recipe.id), method: :delete do %>
                          ♥<%= @recipe.favorites.count %> いいね
                        <% end %>
                      </p>
                      <% else %>
                      <p>
                        <%= link_to users_favorites_path(@recipe), method: :post do %>
                          ♡<%= @recipe.favorites.count %> いいね
                        <% end %>
                      </p>
                    <% end %>
                  </nav>
                </div>
              </article>
            </div>

          </div>

          </div>

        </div>
    </div>


</div>